version: "3.8"
services:
  db:
    container_name: carrentaldb
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: carrental
      POSTGRES_PASSWORD: carrental
      POSTGRES_DB: carrentaldb
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" #SMTP
      - "8025:8025" #UI