import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import ChatModule from "./components/chatModule/chatModule";
import ClientAuthenticationInitializer from "./components/security/clientAuthenticationInitializer";
import { ThemeProvider } from "./components/themeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <main>
            <div className="relative min-h-screen">
              <div className="flex flex-col relative z-10 min-h-screen">
                <ClientAuthenticationInitializer />
                <Header />
                {children}
                <ChatModule />
              </div>
            </div>
          </main>
        </ThemeProvider>

      </body>
    </html>
  );
}
